// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct representing a backend warning.
 */
export type BackendWarning = { 
/**
 * The warning message.
 */
message: string, };
