// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendError } from "./BackendError";
import type { BackendFatal } from "./BackendFatal";
import type { BackendInfo } from "./BackendInfo";
import type { BackendMessage } from "./BackendMessage";
import type { BackendWarning } from "./BackendWarning";
import type { BadFrontendEvent } from "./BadFrontendEvent";
import type { ConnectionCloseOrBroken } from "./ConnectionCloseOrBroken";
import type { ConnectionInfo } from "./ConnectionInfo";
import type { ConnectionRequestResponse } from "./ConnectionRequestResponse";
import type { FileOffer } from "./FileOffer";
import type { FileTransferComplete } from "./FileTransferComplete";
import type { FileTransferError } from "./FileTransferError";
import type { FileTransferProgress } from "./FileTransferProgress";

/**
 * Enum of events that occur in the backend and should be sent to the frontend.
 */
export type BackendEvent = { "type": "BackendError" } & BackendError | { "type": "BackendFatal" } & BackendFatal | { "type": "BackendReady" } & BackendInfo | { "type": "BackendShutdown" } | { "type": "BackendWarning" } & BackendWarning | { "type": "BadFrontendEvent" } & BadFrontendEvent | { "type": "ConnectRequest" } & ConnectionInfo | { "type": "ConnectionRequestResponse" } & ConnectionRequestResponse | { "type": "AutoConnectionClose" } & ConnectionInfo | { "type": "ConnectionClose" } & ConnectionCloseOrBroken | { "type": "ConnectionBroken" } & ConnectionCloseOrBroken | { "type": "FileOffer" } & FileOffer | { "type": "FileTransferComplete" } & FileTransferComplete | { "type": "FileTransferError" } & FileTransferError | { "type": "FileTransferProgress" } & FileTransferProgress | { "type": "Message" } & BackendMessage;
