// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct representing a backend fatal/panic.
 */
export type BackendFatal = { 
/**
 * The error message.
 */
message: string, };
