// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct representing the configuration for the backend startup.
 */
export type BackendStartupConfig = { 
/**
 * Socket address to bind to. (e.g. "0.0.0.0:8080 or [::1]:8080")
 */
bind_addr: string, };
