// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct representing backend information.
 */
export type BackendInfo = { 
/**
 * The version of the backend.
 */
version: string, };
