// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct representing a backend error.
 */
export type BackendError = { 
/**
 * The error message.
 */
message: string, };
