// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontendEvent } from "./FrontendEvent";

/**
 * Struct representing a bad frontend event.
 */
export type BadFrontendEvent = { 
/**
 * Frontend event that was received.
 */
event: FrontendEvent, 
/**
 * The error message.
 */
error: string, };
