// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct representing a file transfer cancellation.
 */
export type CancelFileTransfer = { 
/**
 * The unique identifier of the file transfer to cancel.
 */
unique_id: bigint, 
/**
 * Optional message to send with the cancellation.
 */
message: string | null, };
