// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct representing a connection info.
 */
export type ConnectionInfo = { 
/**
 * The name of the connection.
 */
name: string, 
/**
 * The IP address of the connection.
 */
ip: string, 
/**
 * The version of the backend.
 */
backend_version: string, 
/**
 * The ECDSA public key of the connection.
 * As a string encoded in base64.
 */
identitiy: string, };
