// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct representing a connection request response.
 */
export type ConnectionRequestResponse = { 
/**
 * The IP address of the peer to connect to.
 */
ip: string, 
/**
 * Whether the connection request is accepted.
 */
accept: boolean, 
/**
 * Optional message to send with the connection request response if rejected.
 * Ignored if accept is true.
 */
message: string | null, };
