// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct representing a connection request rejection.
 */
export type ConnectionRequestResponse = { 
/**
 * Accepted or rejected?
 */
accept: boolean, 
/**
 * The IP address of the peer that rejected the connection request.
 */
ip: string, 
/**
 * The reason for the rejection.
 */
reason: string | null, };
