// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct representing a connection request.
 */
export type ConnectRequest = { 
/**
 * The IP address of the peer to connect to.
 */
ip: string, };
