// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct representing a disconnection request.
 */
export type DisconnectRequest = { 
/**
 * The IP address of the peer to disconnect from.
 */
ip: string, 
/**
 * Optional message to send with the disconnection.
 */
message: string | null, };
