// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileTransferDirection } from "./FileTransferDirection";

/**
 * Struct representing a file transfer progress update.
 */
export type FileTransferProgress = { 
/**
 * The unique identifier of the file being transferred.
 */
unique_id: bigint, 
/**
 * The number of bytes transferred so far.
 */
bytes_transferred: bigint, 
/**
 * The total number of bytes to transfer.
 */
total_bytes: bigint, 
/**
 * Sending or receiving the file?
 */
sending: FileTransferDirection, };
