// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct representing a file offer response.
 */
export type FileOfferResponse = { 
/**
 * The unique identifier of the file being offered.
 */
unique_id: bigint, 
/**
 * Whether the file offer is accepted.
 */
accept: boolean, };
