// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionInfo } from "./ConnectionInfo";

/**
 * Struct representing a file offer.
 */
export type FileOffer = { 
/**
 * The peer that is offering the file.
 */
peer: ConnectionInfo, 
/**
 * The filename of the file being offered.
 */
filename: string, 
/**
 * A unique identifier for the file.
 */
unique_id: bigint, 
/**
 * The size of the file in bytes.
 */
size: bigint, };
