// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct representing a file transfer completion.
 */
export type FileTransferComplete = { 
/**
 * The unique identifier of the file that was transferred.
 */
unique_id: bigint, };
