// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct representing a file transfer error.
 */
export type FileTransferError = { 
/**
 * The unique identifier of the file that had an error.
 */
unique_id: bigint, 
/**
 * The error message.
 */
message: string, };
