// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CancelFileTransfer } from "./CancelFileTransfer";
import type { FileOfferResponse } from "./FileOfferResponse";
import type { TransmitFile } from "./TransmitFile";

/**
 * Enum of events that occur in the frontend and should be sent to the backend.
 */
export type FrontendEvent = { "type": "TransmitFile" } & TransmitFile | { "type": "FileOfferResponse" } & FileOfferResponse | { "type": "CancelFileTransfer" } & CancelFileTransfer;
