// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct representing a file transmission request.
 */
export type TransmitFile = { 
/**
 * The absolute path to the file to transmit.
 */
path: string, 
/**
 * The filename to transmit.
 */
filename: string, };
